import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Sidebar HTML: Hanya mengambil isi folder docs/html
  htmlSidebar: [
    {
      type: 'autogenerated',
      dirName: 'html', 
    },
  ],

  // Sidebar CSS: Hanya mengambil isi folder docs/css
  cssSidebar: [
    {
      type: 'autogenerated',
      dirName: 'css',
    },
  ],
};

export default sidebars;